name: Get container app variables
description: 'Get the variables needed to deploy the container app'

inputs:
  app-name:
    description: The name of the app being deployed
    required: true
    type: string
  environment:
    description: The environment being deployed to
    required: true
    type: string
  service-type:
    description: The service type being deploy - Api, Worker etc.
    required: true
    type: string
  branch-suffix:
    description: The suffix to add to resources for branch releases.
    required: true
    type: string
outputs:
  container-app-exists:
    value: ${{ steps.build-ca-variables.outputs.container-app-exists }}
  container-app-image:
    value: ${{ steps.build-ca-variables.outputs.container-app-image }}
  container-app-name:
    value: ${{ steps.build-ca-variables.outputs.container-app-name }}

runs:
  using: "composite"
  steps:
  - id: build-ca-variables
    shell: bash
    run: |
      serviceTypePreFormatting=${{ inputs.service-type }}
      serviceType="${serviceTypePreFormatting,,}"
      containerAppImage="${{ inputs.app-name }}-$serviceType"
      containerAppGroupName="ca-${{ inputs.app-name }}-${{ inputs.environment }}${{ inputs.branch-suffix }}"
      containerAppName="ca-${{ inputs.app-name }}-$serviceType-${{ inputs.environment }}${{ inputs.branch-suffix }}"
      if [[ $resourceGroupExists == 0 ]]; then
        containerAppId=""
        containerAppExists=0
      else
        containerAppId="$(az containerapp list -g $resourceGroupName --query '[?name==`'$containerAppName'`].id | [0]')"
        containerAppExists="$([[ $containerAppId == '' ]] && echo 0 || echo 1)"
      fi
      echo "container-app-exists=$containerAppExists" >> $GITHUB_OUTPUT
      echo "container-app-image=$containerAppImage" >> $GITHUB_OUTPUT
      echo "container-app-name=$containerAppName" >> $GITHUB_OUTPUT
